# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cbec4265a0f088fbe00519120ffe52b6b81703fb30a70f163e64e1694e15d6906801b251459071e0b2199e35318c9bfaa5d0bf1dfe159ea734c97ce184827f3

test:
  secret_key_base: ba4ed299782133467d71f0a7f0d7c3a134eb101d1c534cb9b4b053bc9cdd0354e45c5f22701485a0819b884b1954897aaaa15261ff7a1c2e297f28a82169c042

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
